# Generated by Django 3.2.9 on 2021-11-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('imagen', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
